
- hosts: localhost
  gather_facts: no
  vars_files:
          - ansible.yml
  tasks:
  - name: Launching ec2 Instance 
    ec2:
      key_name: "key17"
      instance_type: "t2.micro"
      image: "ami-0a780d5bac870126a"
      wait: "yes"
      count: 1
      vpc_subnet_id: "subnet-08b4d598b90fe1eac"
      assign_public_ip: yes
      region: "ap-south-1"
      state: present
      group_id: "sg-0472fcae5f298fbe5"
      aws_access_key: "{{ user }}"
      aws_secret_key: "{{ pass }}"
    register: ec2
  - debug:
      var: ec2.instances[0].public_ip
  - name: Adding ec2 Instance to Host Group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: ec2_login
    with_items: "{{ ec2.instances }}"
  - name: Starting SSH port of ec2 Instance
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"
- hosts: ec2_login
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
  - name: Installing Apache Webserver
    package:
      name: httpd
      state: present
  - name: Starting httpd Services
    service:
      name: httpd
      state: started
      enabled: yes
  - name: Copying Webpages to Apache directory
    copy:
      src: "/root/Ansible-tasks/web.html"
      dest: "/var/www/html"
    
  





   

 
